### ISSUE TITLE
Cannot find module '../../test/Integration/Gateways/Terminals/RequestIdProvider'

### ISSUE THREAD

**Issue by RanvijayChouhan12** [globalpayments/node-sdk#71]
Looks Like test Folder is Missing in the modules, 

i checked the Node-modules but didn't find test Folder anywhere

Please Help with this

ERROR :

Error: Cannot find module '../../test/Integration/Gateways/Terminals/RequestIdProvider'
Require stack:
- /Users/ranvijay/Desktop/RV/test_Global_Pay/node_modules/globalpayments-api/lib/src/Gateways/RestGateway.js
- /Users/ranvijay/Desktop/RV/test_Global_Pay/node_modules/globalpayments-api/lib/src/Gateways/GpApiConnector.js
- /Users/ranvijay/Desktop/RV/test_Global_Pay/node_modules/globalpayments-api/lib/src/Gateways/index.js
- /Users/ranvijay/Desktop/RV/test_Global_Pay/node_modules/globalpayments-api/lib/src/index.js
- /Users/ranvijay/Desktop/RV/test_Global_Pay/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/ranvijay/Desktop/RV/test_Global_Pay/node_modules/globalpayments-api/lib/src/Gateways/RestGateway.js:4:29)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ranvijay/Desktop/RV/test_Global_Pay/node_modules/globalpayments-api/lib/src/Gateways/RestGateway.js',
    '/Users/ranvijay/Desktop/RV/test_Global_Pay/node_modules/globalpayments-api/lib/src/Gateways/GpApiConnector.js',
    '/Users/ranvijay/Desktop/RV/test_Global_Pay/node_modules/globalpayments-api/lib/src/Gateways/index.js',
    '/Users/ranvijay/Desktop/RV/test_Global_Pay/node_modules/globalpayments-api/lib/src/index.js',
    '/Users/ranvijay/Desktop/RV/test_Global_Pay/index.js'
  ]
}

MY CODE 🥇 

const express = require("express");
const GlobalPayments = require("globalpayments-api");
const app = express();

app.use(express.json());

app.post("/create-payment", async (req, res) => {
  try {
    const { cardNumber, expiry, cvv, amount } = req.body;
    const response = await GlobalPayments.cards.charge({
      cardNumber,
      expiry,
      cvv,
      amount,
      currency: "USD",
    });

    if (response.isSuccessful) {
      res.json({ transactionId: response.transactionId });
    } else {
      res.status(400).json({ message: response.message });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

app.listen(3000, () => console.log("Server running on port 3000"));

**Comment by matrix125** [comment]
Please use this version:   "globalpayments-api": "3.5.1-fix-4".
A fix is being worked on and may be released this Thursday 5/30.

**Comment by RanvijayChouhan12** [comment]
Thanks Above Solved the Previous Issue 

but Now i am getting some new Error

const config = new ServicesConfig()
               ^

TypeError: ServicesConfig is not a constructor
    at Object.<anonymous> (/Users/ranvijay/Desktop/RV/test_Global_Pay/index.ts:37:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
    
    
    My CODE 👍🏻 


const config = new ServicesConfig()
  .setServiceUrl(Environment.Sandbox)
  .setLicenseId("") // Replace with your License ID
  .setSiteId("") // Replace with your Site ID
  .setMerchantId("") // Replace with your Merchant ID
  .setPassword(""); 
  
  Also if you could help me , Which Fileld will have What Values and Where i can get them
  
  
  thanks,

**Comment by matrix125** [comment]
Hi,

Going forward, please send all inquiries to the developers group directly.
https://developer.heartlandpaymentsystems.com/Support

Specifically: [developers@heartland.us](mailto:developers@heartland.us)

With regards to your issue. Use the below.

const config = new PorticoConfig();
config.secretApiKey =  "skapi_cert_your secret api key"
config.developerId = '000000'; // your dev id, if you start the cert process and recived one, else use these values
config.versionNumber = '0000'; // your dev version id, if you start the cert process and recived one, else use these values
config.serviceUrl = 'https://cert.api2.heartlandportico.com'; 
ServicesContainer.configureService(config);
